# Permalinks
permalink:pretty
relative_permalinks:true

# Setup
title:Emily Saliba
tagline: UNDER CONSTRUCTION
url:http://emilysaliba.com
paginate:1
name:Emily Saliba
  #url:https://twitter.com/
  email:emilysquid@gmail.com

# Custom vars
version:1.0.0
#github:
  repo:https://github.com/emilysquid

#highlighter: null
lsi:false
#permalink:/:year/:month/:day/:title.html
markdown:rdiscount
rdiscount:
  extensions:[smart]
