# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Emily Saliba
tagline:          Under Construction
url:              http://emilysaliba.com
paginate:         1
baseurl:          /
author:
  name:           Emily Saliba
  #url:            https://twitter.com/
  email:          emilysquid@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/emilysquid
